### ISSUE TITLE
Apache Big Data Europe 2016

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump-voice#4]
[CFP](http://events.linuxfoundation.org/events/apache-big-data-europe/program/cfp) closes Sept 9th

**Comment by manuzhang** [comment]
the proposal has been accepted

**Comment by whjiang** [comment]
Great！！！

发件人: ManuZhang notifications@github.com
答复: gearpump/gearpump-voice reply@reply.github.com
日期: 2016年9月29日 星期四 下午3:42
至: gearpump/gearpump-voice gearpump-voice@noreply.github.com
主题: Re: [gearpump/gearpump-voice] Apache Big Data Europe 2016 (#4)

the proposal has been accepted

**Comment by kkasravi** [comment]
That's awesome Manu! 

```
On Thursday, September 29, 2016 12:42 AM, ManuZhang <notifications@github.com> wrote:
```

 the proposal has been accepted —
