### ISSUE TITLE
Big Data Tech Warsaw 2017

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump-voice#9]
CFP http://bigdatatechwarsaw.eu/cfp/ deadline is Nov.11th, 2016

**Comment by karol-brejna-i** [comment]
Is there a chance someone of you could speak at Warsaw ( @manuzhang @kkasravi @huafengw ), too ?

I'll prepare an abstract today (CET ;-) ). Tomorrow we can discuss this on our meeting (I set up a meeting tomorrow on 7:00 AM CET) and decide on if/what to submit.

The questionnaire goes like this:

> 1. Name of the speaker
>    (if there is more than one speaker proposed please add number (like 1.) for each name and then accordingly for other fields related to speaker, like bio).
> 2. Proposed title of the presentation
> 3. Description of the presentation
>    (more detailed description of your presentation (3-6 paragraph)  to help the program committee and potential attendees to understand what you will cover).
> 4. Which conference track would be perfect fit for this presentation?
>    (for detailed description of the sessions please look at the webpage - http://bigdatatechwarsaw.eu/agenda/)
>    Operations & Deployment
>    Hadoop Application Development
>    Analytics & Data Science
>    Real-Time Processing
> 5. Audience information
>    (who the presentation is for?)
> 6.  How would you rank your presentation: 1- very technical, 5 - only business related
> 7. Please give us up to 4 keywords describing your presentation
> 8. Speaker bio
> 9. Speaker's experience
>    (provide any information about your previous speaking experience at public conferences, meetups and/or workshops. Links to YouTube videos or your conference talks are welcomed)
> 10. Additional information
>     (any other information that support your submission and profile)
> 11. Speaker e-mail contact address
> 12. Speaker formal position and company name
> 13. Do you have any other comments, questions, or concerns?

**Comment by karol-brejna-i** [comment]
Submission deadline is 11th Nov, but Big Data Technology Warsaw Summit 2017 will be held 9th of February 2017.
